### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by timothyslau** [mrxiaohe/WRScpp#2]
When I run:
install_github(repo = "mrxiaohe/WRScpp")

I'm getting:
* installing *binary* package 'WRScpp' ...

ERROR: installing binary package failed
* removing 'C:/Program Files/R/R-3.0.2/library/WRScpp'

Error: Command failed (1)

**Comment by mrxiaohe** [comment]
Hi Timothy, 

Sorry for this late reply. (For some reason I never got a notification for your post). WRScpp only works for Mac. Since you have a PC, can you try https://github.com/mrxiaohe/WRScppWin

**Comment by monasorjja** [comment]
https://github.com/mrxiaohe/WRScppWin fails on win10
